version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'hydra'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  hydra-migrate:
    image: oryd/hydra:v1.0.0
    environment:
      DSN: "mysql://user:secret@tcp(db:3306)/hydra?tls=false"
    command: migrate sql -e --yes
    depends_on:
      - db
